# Generated by Django 2.0.3 on 2019-03-31 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20190318_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(related_name='prod', to='main.Product')),
            ],
        ),
    ]
